name: FTP Deploy

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_HOST }}  # Using the FTP host from secrets
        username: ${{ secrets.FTP_USERNAME }}  # FTP username from secrets
        password: ${{ secrets.FTP_PASSWORD }}  # FTP password from secrets
        local-dir: ./  # Upload everything from the repository
        server-dir: ${{ secrets.FTP_PATH }}  # Make sure this path is correct on your server (e.g., /public_html)
        port: ${{ secrets.FTP_PORT }}  # FTP port (e.g., 21)
        # Optional: remove this line if not needed
        git-ftp-args: "--insecure"  # Use only if your FTP server has issues with SSL

