name: FTP Deploy

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_HOST }}  # Updated key to 'server'
        username: ${{ secrets.FTP_USERNAME }}  # Updated key to 'username'
        password: ${{ secrets.FTP_PASSWORD }}  # Updated key to 'password'
        local-dir: ./ # Upload everything from the repository
        server-dir: ${{ secrets.FTP_PATH }} # Destination path on your server
        port: ${{ secrets.FTP_PORT }}  # Set the FTP port
        git-ftp-args: "--insecure" # Optional argument for some FTP servers
